MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,37 +8,58 @@ osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=35
-    - CONDA_PY=36
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "VIn4LS0eys4MUHG5NLKU7fFu4KgVuA8UJqjgv739dEJYR4ZUwvVIrq/DluauUc98gnMO3eDFrWI9LS4VygPcdOQazlr1QxgR7sCdjtqdXz2A3vVHzYZzMUdPv/p0hQCaGLIV7ssc144B+CzOFXj8whvwNI5k2/EjllIUo22VtboIIFOpbQCazz7ZgxwfY/J70WO8GKU5gBhISafes5LBPHEpKQJfPAp/uWq4A6uC6EvSbaJ87+rXmeYL98eRCQb88DKWeO/I/w53okc072uCps9fApgQ8clCwreUlC80/dnVS1ZVUKjzybCwI8S+v96CN7QItNfHVKdYVKrMQDuHKm6YLw5S3LVnLKfdReXVHxs7qpeZNUqQsoBbjNgjZTMAVWHhtMA7HqioDnDzYHmgZnWffLH10KhRn5kuo2iKZIH6j/WaFswl74Lm3OR1DqN8VZ5BrXYS0iIoc2xb+B2AKuq/mAQDhMhpUSFWHY4lZar4VOPVihv1JNJfcOqH2ya2TyMTtrGOCmCQ70w52H03irmKYOu26KnEtYkJVp/e5+vanCZAFK5lDNHZZN0EyKnlpmnd5eP0zePCZkyWetL3zLaRBTFTTewXFs6TVg/j1yb3cByRIGcvKwIc131IPengdWfDXcLqdaVAVzqnkHBxKKdFcbvMcxLk9/Zuda3Lr2o="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force --ignore-dependencies $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
